### ISSUE TITLE
Please add a regular package outside the Microsoft Appsource Store

### ISSUE THREAD

**Issue by DuncanLithgow** [specklesystems/speckle-excel#30]
Please add a regular package outside the Microsoft Appsource Store. For two reasons, I shouldn't have to create an account to access these connectors, but also because they require all sorts of information before I can make the download.

![billede](https://user-images.githubusercontent.com/3223028/145269004-7b0040d1-69f5-41e8-9f4f-52971b694983.png)

**Comment by teocomi** [comment]
Hey @DuncanLithgow unfortunately, that is the only "proper" mechanism Microsoft allows to deploy JS based office plugins, the only other alternative I'm aware of is sideloading locally the plugin.

Keen to explore other solutions you might discover!

**Comment by DuncanLithgow** [comment]
Sounds like the same problems Yousheng has been having with IfcToolbox https://bimmars.com/ifctoolbox_openbim/

But I know nothing about this - I just know it's also a problem at my end as a user / tester. I won't able to install it without some nightmare discussion with my IT support people.
