### ISSUE TITLE
Send with headers should send objects with `speckle_type` when none is found.

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-excel#40]
Reported in https://speckle.community/t/excel-grasshopper/4251/2

Excel with headers will send objects without a `speckle_type`. These will be converted as `Dictionary<string,object>` when received in C#, which can break some workflows.

Since excel data is usually pretty dumb (raw data in col/rows), this is not a huge issue per-se, but when receiving in GH it becomes clear that something weird is happening.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
