### ISSUE TITLE
Saved streams improvements

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-excel#42]
With the new UI & navigation, saved streams could do with some improvements:
- automatically show them at the top of the "all streams" list (I think it was working last time, but it's not now)
- have a simple way for ppl to recognize which are saved streams
- let ppl remove saved streams and remove them; since they are serialized inside the Sheet, they could add some noise if not needed anymore...

We have played with the concept of "pinning" streams; maybe that's the way to go? This can probably wait for the DUI redesign so we can proceed with a shared strategy/UI.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
